language: python
env:
   - DJANGO='>=1.8,<1.9'
   - DJANGO='>=1.9,<1.10'
   - DJANGO='>=1.10,<1.11'
   - DJANGO='>=1.11,<1.12'
python:
   - "2.7"
   - "3.6"
install:
   - pip install -e .
   - pip install -r requirements/requirements_test.txt
   - pip install "Django${DJANGO}"
before_script:
    # All migrations have to be generated
    - (! python test_project/manage.py makemigrations --dry-run --exit)
    - flake8 locking/
script:
    pytest -v --capture=sys --cov=locking/ locking/ --cov-report term-missing:skip-covered
after_success:
    coveralls
